version: '3'

services:
  nginx:
    hostname: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    environment:
      SERVER_DOMAIN: ${SERVER_DOMAIN:-localhost}
      APP_DOMAIN: ${APP_DOMAIN:-app}
    restart: unless-stopped
    volumes:
      - ./nginx/conf/${NGINX_PROTOCOL:-http}.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - ./certbot/log/:/var/log/:rw
    networks:
      bridgenw:

  app:
    hostname: app
    build:
      dockerfile: Dockerfile
      context: app
    ports:
      - 8000:8000


networks:
  bridgenw:
    driver: bridge
